"""add_metadata_tables

Revision ID: 365fa81e09e0
Revises: 001_initial
Create Date: 2026-01-22 11:31:00.804318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '365fa81e09e0'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_items_asin'), 'local_items', ['asin'], unique=False)
    op.create_index(op.f('ix_local_items_title'), 'local_items', ['title'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_name'), 'series', ['name'], unique=False)
    op.create_table('book_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_assets_asset_type'), 'book_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_book_assets_book_asin'), 'book_assets', ['book_asin'], unique=False)
    op.create_table('book_authors',
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('book_asin', 'person_id')
    )
    op.create_table('book_narrators',
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('book_asin', 'person_id')
    )
    op.create_table('book_scan_state',
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_mtime', sa.Float(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('fast_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('extractor_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.PrimaryKeyConstraint('book_asin')
    )
    op.create_index(op.f('ix_book_scan_state_file_path'), 'book_scan_state', ['file_path'], unique=True)
    op.create_table('book_series',
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('series_index', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('book_asin', 'series_id')
    )
    op.create_table('book_technical',
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('extractor_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.PrimaryKeyConstraint('book_asin')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_offset_ms', sa.Integer(), nullable=False),
    sa.Column('length_ms', sa.Integer(), nullable=False),
    sa.Column('end_offset_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_book_asin'), 'chapters', ['book_asin'], unique=False)
    op.create_table('playback_progress',
    sa.Column('book_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('last_chapter_id', sa.Uuid(), nullable=True),
    sa.Column('playback_speed', sa.Float(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_asin'], ['books.asin'], ),
    sa.ForeignKeyConstraint(['last_chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('book_asin')
    )
    op.add_column('app_settings', sa.Column('aaxtomp3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='/usr/local/bin/AAXtoMP3'))
    op.add_column('app_settings', sa.Column('cover_cache_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='/app/data/covers'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'cover_cache_dir')
    op.drop_column('app_settings', 'aaxtomp3_path')
    op.drop_table('playback_progress')
    op.drop_index(op.f('ix_chapters_book_asin'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('book_technical')
    op.drop_table('book_series')
    op.drop_index(op.f('ix_book_scan_state_file_path'), table_name='book_scan_state')
    op.drop_table('book_scan_state')
    op.drop_table('book_narrators')
    op.drop_table('book_authors')
    op.drop_index(op.f('ix_book_assets_book_asin'), table_name='book_assets')
    op.drop_index(op.f('ix_book_assets_asset_type'), table_name='book_assets')
    op.drop_table('book_assets')
    op.drop_index(op.f('ix_series_name'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_local_items_title'), table_name='local_items')
    op.drop_index(op.f('ix_local_items_asin'), table_name='local_items')
    op.drop_table('local_items')
    # ### end Alembic commands ###
