"""add_scan_job_type

Revision ID: d38dcf655434
Revises: 365fa81e09e0
Create Date: 2026-01-22 13:49:33.482999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd38dcf655434'
down_revision: Union[str, None] = '365fa81e09e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'SCAN'")
    op.alter_column('app_settings', 'aaxtomp3_path',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('app_settings', 'cover_cache_dir',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_settings', 'cover_cache_dir',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'/app/data/covers'::character varying"),
               existing_nullable=False)
    op.alter_column('app_settings', 'aaxtomp3_path',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'/usr/local/bin/AAXtoMP3'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
